# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff6eddc7ea21f616d7a12123853dc7e7"
name = "Payment Customization App"
application_url = "https://petersburg-apple-shades-qualifications.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mehul-checkout-extensions.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_payment_customizations,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://petersburg-apple-shades-qualifications.trycloudflare.com/auth/callback",
  "https://petersburg-apple-shades-qualifications.trycloudflare.com/auth/shopify/callback",
  "https://petersburg-apple-shades-qualifications.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
